### ISSUE TITLE
Modules to delete that still contain items

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/action-series-modules#2]
https://github.com/byuitechops/action-series-modules/blob/9bb617d7fbbd10cb572a57837e38736549e77eab/actions/modules-delete.js#L22-L26

Can we add a parameter to the condition that the module must be empty? I don't think it will delete it without a special query parameter in the URI if there are items in it, but to prevent it from throwing errors at us. If there are items in the module, log a warning.

**Comment by sethchilders92** [comment]
@zlw11063 Do we even need this? Sam and I deleted the Welcome Module and the Resources Module in Disperse-Welcome-Folder already, which are the only two we have to delete. Otherwise wouldn't we have to do a get request to check the number of module items in it? Or we could modify template-modules.js to save that data to the TechOps class.

**Comment by zachintosh** [comment]
Good point. I think its fine how it is.
